"use client";
import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { ActionButton } from "@/src/components/ui/Button";
import { Field, TextareaField } from "@/src/components/forms/FormFields";
const schema = z.object({ name: z.string().min(2, "Please enter your name"), email: z.string().email("Enter a valid email"), country: z.string().min(2, "Country is required"), company: z.string(), interest: z.string().min(2, "Tell us your interest"), message: z.string().min(10, "Please add a little more detail"), lookId: z.string(), consent: z.literal(true, { error: "Consent is required" }), website: z.string().max(0) });
type Values = z.infer<typeof schema>;
export function InquiryForm({ lookId }: { lookId: string }) { const { register, handleSubmit, formState:{ errors, isSubmitting, isSubmitSuccessful } } = useForm<Values>({ resolver:zodResolver(schema), defaultValues:{ name:"", email:"", country:"", company:"", interest:"Private viewing", message:"", lookId, website:"" } }); const submit = async (values: Values) => { const r = await fetch("/api/contact", { method:"POST", headers:{"content-type":"application/json"}, body:JSON.stringify(values) }); if (!r.ok) throw new Error("Request failed"); }; if (isSubmitSuccessful) return <div role="status" className="py-16"><h3 className="font-display text-5xl">Request received.</h3><p className="mt-4 text-black/55">The studio will review your enquiry. No email has been sent in this mock phase.</p></div>; return <form onSubmit={handleSubmit(submit)} className="grid gap-6 sm:grid-cols-2" noValidate><Field label="Name" error={errors.name} register={register("name")}/><Field label="Email" type="email" error={errors.email} register={register("email")}/><Field label="Country" error={errors.country} register={register("country")}/><Field label="Company / Organisation" error={errors.company} register={register("company")}/><div className="sm:col-span-2"><Field label="Interest" error={errors.interest} register={register("interest")}/></div><div className="sm:col-span-2"><TextareaField label="Message" error={errors.message} register={register("message")}/></div><input type="hidden" {...register("lookId")}/><input className="hidden" tabIndex={-1} {...register("website")}/><label className="flex items-start gap-3 text-xs leading-5 sm:col-span-2"><input type="checkbox" className="mt-1" {...register("consent")}/>I consent to Batik NXT using these details to respond to this enquiry.</label>{errors.consent && <p role="alert" className="text-xs text-deep-red sm:col-span-2">{errors.consent.message}</p>}<ActionButton disabled={isSubmitting} className="sm:col-span-2">{isSubmitting ? "Submitting…" : "Send enquiry"}</ActionButton></form>; }
