import type { Metadata } from "next";
import Image from "next/image";
import { notFound } from "next/navigation";
import { LooksGallery } from "@/src/components/collection/LooksGallery";
import { Container } from "@/src/components/ui/Container";
import { getCollectionBySlug, getCollections } from "@/src/lib/repositories/collection-repository";
import { getLooksByCollection } from "@/src/lib/repositories/look-repository";
export async function generateStaticParams() { return (await getCollections()).map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{slug:string}> }): Promise<Metadata> { const c = await getCollectionBySlug((await params).slug); return c ? { title: c.seo.title, description: c.seo.description } : {}; }
export default async function CollectionPage({ params }: { params: Promise<{slug:string}> }) { const collection = await getCollectionBySlug((await params).slug); if (!collection) notFound(); const [looks, all] = await Promise.all([getLooksByCollection(collection.id), getCollections()]); const next = all[(all.findIndex((x) => x.id === collection.id) + 1) % all.length]; return <><section className="relative min-h-[100svh] bg-black text-ivory"><Image src={collection.heroMedia.src} alt={collection.heroMedia.alt} fill priority sizes="100vw" className="object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-black/85 via-transparent to-black/25"/><Container className="absolute inset-x-0 bottom-12"><p className="text-[10px] uppercase tracking-[.22em]">Collection {collection.number} · {collection.year} · {collection.category}</p><h1 className="mt-5 font-display text-[clamp(4rem,11vw,11rem)] uppercase leading-[.72] tracking-[-.055em]">{collection.title}</h1><p className="mt-7 max-w-xl text-sm leading-6 text-white/65">{collection.description}</p></Container></section><section className="bg-ivory py-24 text-black sm:py-36"><Container><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><h2 className="font-display text-6xl uppercase">The story</h2><div className="space-y-7 text-lg leading-8 text-black/65">{collection.story.map((x) => <p key={x}>{x}</p>)}<dl className="grid gap-6 border-t border-black/15 pt-8 text-sm sm:grid-cols-3"><div><dt className="label">Materials</dt><dd>{collection.materials.join(", ")}</dd></div><div><dt className="label">Motifs</dt><dd>{collection.motifs.join(", ")}</dd></div><div><dt className="label">Palette</dt><dd className="mt-2 flex gap-2">{collection.palette.map((x) => <span key={x} className="size-6 rounded-full border border-black/15" style={{background:x}} aria-label={x}/>)}</dd></div></dl></div></div></Container></section><section className="bg-black py-24 text-ivory"><Container><LooksGallery looks={looks}/></Container></section><a href={`/collections/${next.slug}`} className="group relative block h-[70svh] overflow-hidden"><Image src={next.coverImage.src} alt={next.coverImage.alt} fill sizes="100vw" className="object-cover transition duration-1000 group-hover:scale-105"/><div className="absolute inset-0 bg-black/45"/><div className="absolute inset-0 flex flex-col items-center justify-center text-ivory"><p className="text-[10px] uppercase tracking-[.22em]">Next collection</p><h2 className="mt-5 font-display text-6xl uppercase sm:text-9xl">{next.title}</h2></div></a></>; }
