"use client";
import { AnimatePresence, motion } from "motion/react";
import { Search, X } from "lucide-react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useEffect, useState } from "react";
import { navigation } from "@/src/data/navigation";
import { socialLinks } from "@/src/data/social-links";
import { SearchOverlay } from "./SearchOverlay";

export function Header() {
  const [scrolled, setScrolled] = useState(false); const [menu, setMenu] = useState(false); const [search, setSearch] = useState(false); const pathname = usePathname();
  useEffect(() => { const scroll = () => setScrolled(window.scrollY > 30); scroll(); addEventListener("scroll", scroll, { passive: true }); return () => removeEventListener("scroll", scroll); }, []);
  useEffect(() => setMenu(false), [pathname]);
  useEffect(() => { if (!menu) return; document.body.style.overflow = "hidden"; const key = (e: KeyboardEvent) => e.key === "Escape" && setMenu(false); document.addEventListener("keydown", key); return () => { document.body.style.overflow = ""; document.removeEventListener("keydown", key); }; }, [menu]);
  return <><header className={`fixed inset-x-0 top-0 z-50 flex h-20 items-center justify-between px-5 text-ivory transition sm:px-8 lg:h-22 lg:px-12 ${scrolled ? "border-b border-white/10 bg-black/75 backdrop-blur-xl" : ""}`}><Link href="/" className="wordmark relative z-10 text-sm sm:text-base" aria-label="Batik NXT home">BATIK NXT</Link><nav className="hidden items-center gap-7 lg:flex" aria-label="Primary navigation">{navigation.map((item) => <Link key={item.href} href={item.href} className={`nav-link ${pathname.startsWith(item.href) ? "text-white" : "text-white/65"}`}>{item.label}</Link>)}</nav><div className="flex items-center gap-4"><button onClick={() => setSearch(true)} aria-label="Open search" className="hidden p-2 sm:block"><Search className="size-4" /></button><Link href="/contact" className="nav-link hidden sm:block">Contact</Link><button onClick={() => setMenu((v) => !v)} className="relative z-10 flex h-10 w-12 flex-col items-end justify-center gap-1.5 lg:hidden" aria-expanded={menu} aria-controls="fullscreen-menu" aria-label={menu ? "Close menu" : "Open menu"}>{menu ? <X className="size-6" /> : <><span className="h-px w-7 bg-current"/><span className="h-px w-4 bg-current"/></>}</button></div></header><AnimatePresence>{menu && <motion.div id="fullscreen-menu" className="fixed inset-0 z-40 bg-black px-5 pb-8 pt-28 text-ivory sm:px-10" initial={{ clipPath: "inset(0 0 100% 0)" }} animate={{ clipPath: "inset(0 0 0% 0)" }} exit={{ clipPath: "inset(0 0 100% 0)" }} transition={{ duration: .7, ease: [.76,0,.24,1] }} role="dialog" aria-modal="true"><nav className="flex flex-col">{navigation.map((item, i) => <motion.div key={item.href} initial={{ y: 30, opacity: 0 }} animate={{ y: 0, opacity: 1 }} transition={{ delay: .1 + i * .05 }}><Link href={item.href} className="flex items-baseline gap-4 border-b border-white/15 py-3 font-display text-[clamp(2.5rem,10vw,6rem)] leading-none"><span className="font-sans text-[9px] tracking-[.2em] text-white/40">0{i + 1}</span>{item.label}</Link></motion.div>)}</nav><div className="absolute bottom-8 left-5 right-5 flex flex-wrap justify-between gap-5 border-t border-white/15 pt-5 text-[10px] uppercase tracking-[.18em] text-white/55 sm:left-10 sm:right-10"><div className="flex gap-5">{socialLinks.slice(0, 2).map((x) => <a key={x.label} href={x.href}>{x.label}</a>)}</div><span>Malaysia · English</span></div></motion.div>}</AnimatePresence><SearchOverlay open={search} onClose={() => setSearch(false)} /></>;
}
